// SAMPLE TRIP DATA — everything in this file with `isSample: true` is
// placeholder content (dates, prices, seat counts, inclusions) for
// demonstrating the site. Replace with real trips before launch.
// To add a new trip: copy an object below, give it a new unique `slug`,
// and it will automatically appear on /trips and get its own /trips/[slug] page.
// No other file needs to change.

export type TripCategory =
  | "Bike Rides"
  | "One Day"
  | "Weekend"
  | "2 Days"
  | "Weekday"
  | "Adventure"
  | "Heritage"
  | "Nature"
  | "Trek"
  | "Camping"
  | "Coastal"
  | "Wildlife"
  | "Temple Trails"
  | "Long Weekend";

export type BookingStatus = "open" | "few-left" | "sold-out" | "closed";

export interface ItineraryItem {
  time: string;
  label: string;
}

export interface ItineraryDay {
  day: number;
  title: string;
  items: ItineraryItem[];
}

export interface FAQItem {
  question: string;
  answer: string;
}

export interface Trip {
  id: string;
  slug: string;
  title: string;
  destination: string;
  startingPoint: string;
  date: string; // display string — a real fixed date once you have one (e.g. "18-19 Oct 2026"), or "Next batch — ask on WhatsApp" until then
  duration: string; // e.g. "2 Days / 1 Night"
  transport: "Bike" | "Tempo Traveller" | "Bus" | "Bike or Tempo Traveller";
  price: number; // per person, INR
  seatsTotal: number;
  seatsLeft: number;
  bookingStatus: BookingStatus;
  difficulty: "Easy" | "Moderate" | "Challenging";
  stay: string;
  food: string;
  categories: TripCategory[];
  coverImageLabel: string; // placeholder label until real photography exists
  coverImage?: string; // real photo path (public/), once available — falls back to the placeholder when unset
  gallery: string[]; // placeholder labels
  description: string[]; // paragraphs
  highlights: string[];
  itinerary: ItineraryDay[];
  inclusions: string[];
  exclusions: string[];
  whoFor: string[];
  faqs: FAQItem[];
  isSample: true;
}

export const trips: Trip[] = [
  {
    id: "t1",
    slug: "sakleshpur-weekend-ride",
    title: "Sakleshpur Weekend Ride",
    destination: "Sakleshpur, Karnataka",
    startingPoint: "Bengaluru (assembly point shared after booking)",
    date: "Next batch — ask on WhatsApp",
    duration: "2 Days / 1 Night",
    transport: "Bike",
    price: 4999,
    seatsTotal: 20,
    seatsLeft: 6,
    bookingStatus: "few-left",
    difficulty: "Moderate",
    stay: "Homestay, twin sharing",
    food: "Breakfast and dinner included, lunch stops are pay-as-you-go",
    categories: ["Bike Rides", "Weekend", "2 Days", "Nature", "Adventure"],
    coverImageLabel: "Riders on the Sakleshpur ghat road, misty coffee estates",
    coverImage: "/photos/sakleshpur-ghat-road.jpg",
    gallery: [
      "Group photo at the first breakfast stop",
      "Bikes lined up outside a homestay",
      "Waterfall trek on day 2",
    ],
    description: [
      "Leave Bengaluru before the city wakes up, ride through coffee country, stop for filter coffee where the estate owner still roasts it themselves, and spend the afternoon at a waterfall most tourists never find.",
      "This is the ride we send people on when they say they want to actually feel like they went somewhere, not just drove somewhere. Rolling ghat roads, real elevation change, and a homestay dinner that beats every restaurant on the highway.",
    ],
    highlights: [
      "Ghat road riding through coffee and spice estates",
      "A waterfall trek that isn't on the main tourist route",
      "Homestay dinner cooked by the family that owns it",
      "Small group — this trip caps at 20 riders, not 60",
    ],
    itinerary: [
      {
        day: 1,
        title: "Bengaluru to Sakleshpur",
        items: [
          { time: "05:30", label: "Meet at the assembly point, briefing and bike check" },
          { time: "06:00", label: "Depart Bengaluru" },
          { time: "08:30", label: "Breakfast stop — filter coffee and dosa" },
          { time: "12:30", label: "Arrive Sakleshpur, check into homestay" },
          { time: "15:00", label: "Local waterfall visit" },
          { time: "20:00", label: "Dinner at the homestay" },
        ],
      },
      {
        day: 2,
        title: "Sakleshpur exploration and ride back",
        items: [
          { time: "07:00", label: "Breakfast" },
          { time: "08:30", label: "Coffee estate walk" },
          { time: "11:00", label: "Depart for Bengaluru" },
          { time: "13:00", label: "Lunch stop (on your own)" },
          { time: "17:00", label: "Arrive Bengaluru, trip ends" },
        ],
      },
    ],
    inclusions: [
      "Route planning and a lead + sweep rider",
      "1 night homestay, twin sharing",
      "Breakfast (both days) and Day 1 dinner",
      "Waterfall trek guide",
      "Trip WhatsApp group with live updates",
    ],
    exclusions: [
      "Fuel for your own bike",
      "Lunch on both days",
      "Personal expenses and shopping",
      "Anything not explicitly listed above",
    ],
    whoFor: [
      "Riders comfortable with 4-5 hours of ghat-road riding a day",
      "Solo riders looking to join a group",
      "Friends who want the route and stay planned for them",
    ],
    faqs: [
      { question: "Do I need my own bike?", answer: "Yes, this specific trip is ride-your-own-bike. If you don't ride, check our Tempo Traveller trips instead." },
      { question: "Can I come alone?", answer: "Yes — most riders on this trip come solo and ride in the group." },
      { question: "Is this beginner-friendly?", answer: "You should be comfortable riding 200+ km a day on ghat roads. It's not a beginner's first long ride." },
      { question: "What if the weather changes?", answer: "The lead rider makes real-time calls on route changes; the WhatsApp group gets updated immediately." },
      { question: "What's the cancellation policy?", answer: "Full details are on our Cancellation & Refund Policy page — in short, the earlier you cancel, the more you get back, and if Tripshala cancels a trip you get a full refund or a free move to another date." },
    ],
    isSample: true,
  },
  {
    id: "t2",
    slug: "nandi-hills-sunrise-ride",
    title: "Nandi Hills Sunrise Ride",
    destination: "Nandi Hills, Karnataka",
    startingPoint: "Hebbal, Bengaluru",
    date: "Next batch — ask on WhatsApp",
    duration: "Half day (4-5 hours)",
    transport: "Bike",
    price: 799,
    seatsTotal: 15,
    seatsLeft: 15,
    bookingStatus: "open",
    difficulty: "Easy",
    stay: "Not applicable — same-day return",
    food: "Filter coffee stop included, breakfast on your own",
    categories: ["Bike Rides", "One Day", "Nature"],
    coverImageLabel: "Sunrise over the Nandi Hills valley, riders silhouetted",
    coverImage: "/photos/nandi-hills-sunrise.jpg",
    gallery: ["Pre-dawn assembly point", "Valley view from the top", "Group breakfast stop"],
    description: [
      "The ride that started it all — out of the city while it's still dark, up the hill in time to watch the valley catch the first light, back home before most people are out of bed.",
      "No planning, no figuring out where to stop for coffee. Just show up at 4:45am with a full tank.",
    ],
    highlights: [
      "Sunrise from the top, timed precisely",
      "A genuinely good filter coffee stop on the way up",
      "Back home by mid-morning — the whole day is still yours",
    ],
    itinerary: [
      {
        day: 1,
        title: "Sunrise ride",
        items: [
          { time: "04:45", label: "Assemble at Hebbal" },
          { time: "05:00", label: "Depart" },
          { time: "05:45", label: "Coffee stop" },
          { time: "06:15", label: "Reach the top, sunrise" },
          { time: "08:00", label: "Ride back" },
          { time: "09:00", label: "Trip ends" },
        ],
      },
    ],
    inclusions: ["Lead rider", "One coffee stop", "Trip WhatsApp group"],
    exclusions: ["Fuel", "Breakfast", "Entry ticket (if applicable)"],
    whoFor: ["First-timers wanting a low-commitment taste of a Tripshala ride", "Early risers", "Anyone who wants their whole Sunday back"],
    faqs: [
      { question: "Can I bring a friend?", answer: "Yes, just add them when booking so we know the final headcount." },
      { question: "Do I need my own bike?", answer: "Yes, for this ride. It's an easy, short route suitable for less experienced riders." },
      { question: "Where do we meet?", answer: "Exact assembly point in Hebbal shared after booking." },
    ],
    isSample: true,
  },
  {
    id: "t3",
    slug: "coorg-coffee-country-escape",
    title: "Coorg Coffee Country Escape",
    destination: "Coorg (Kodagu), Karnataka",
    startingPoint: "Bengaluru (Tempo Traveller pickup points shared after booking)",
    date: "Next batch — ask on WhatsApp",
    duration: "2 Days / 1 Night",
    transport: "Tempo Traveller",
    price: 6499,
    seatsTotal: 12,
    seatsLeft: 12,
    bookingStatus: "open",
    difficulty: "Easy",
    stay: "Estate homestay, twin/triple sharing",
    food: "Breakfast, dinner and one estate lunch included",
    categories: ["Weekend", "2 Days", "Nature", "Heritage"],
    coverImageLabel: "Coffee estate rows in mist, Coorg",
    coverImage: "/photos/coorg-misty-hills.jpg",
    gallery: ["Group at the estate lunch table", "Abbey Falls", "Sunset from the homestay verandah"],
    description: [
      "You don't need to ride to earn this one. A Tempo Traveller, a good playlist, and a coffee estate that's been in the same family for three generations.",
      "This trip is built for people who want the destination and the people without needing to plan a single stop themselves.",
    ],
    highlights: [
      "A working coffee estate tour with the family that runs it",
      "Abbey Falls and a Raja's Seat sunset stop",
      "Group dinner that turns into the best part of the trip, every time",
    ],
    itinerary: [
      {
        day: 1,
        title: "Bengaluru to Coorg",
        items: [
          { time: "06:00", label: "Depart Bengaluru" },
          { time: "09:00", label: "Breakfast stop" },
          { time: "13:00", label: "Arrive, estate lunch" },
          { time: "15:30", label: "Coffee estate walk and tasting" },
          { time: "18:00", label: "Raja's Seat sunset" },
          { time: "20:00", label: "Group dinner at the homestay" },
        ],
      },
      {
        day: 2,
        title: "Abbey Falls and return",
        items: [
          { time: "08:00", label: "Breakfast" },
          { time: "09:30", label: "Abbey Falls" },
          { time: "12:00", label: "Depart for Bengaluru" },
          { time: "14:00", label: "Lunch stop (on your own)" },
          { time: "19:00", label: "Arrive Bengaluru" },
        ],
      },
    ],
    inclusions: ["Tempo Traveller transport both ways", "1 night stay, twin/triple sharing", "Breakfast (both days), Day 1 lunch and dinner", "Estate tour and tasting"],
    exclusions: ["Day 2 lunch", "Personal expenses", "Entry fees not part of the listed itinerary"],
    whoFor: ["Non-riders who still want the trip planned end to end", "Friend groups and couples", "First-time group travellers"],
    faqs: [
      { question: "Do I need to ride a bike for this?", answer: "No — this trip uses a Tempo Traveller, no riding required." },
      { question: "Can I come alone?", answer: "Yes, solo travellers are common on our Tempo trips." },
      { question: "What's the group size?", answer: "Capped at 12 for this trip." },
    ],
    isSample: true,
  },
  {
    id: "t4",
    slug: "hampi-heritage-weekend",
    title: "Hampi Heritage Weekend",
    destination: "Hampi, Karnataka",
    startingPoint: "Bengaluru",
    date: "Next batch — ask on WhatsApp",
    duration: "2 Days / 1 Night",
    transport: "Bus",
    price: 5499,
    seatsTotal: 30,
    seatsLeft: 22,
    bookingStatus: "open",
    difficulty: "Easy",
    stay: "Budget-comfort guesthouse, twin sharing",
    food: "Breakfast included, other meals on your own at local eateries",
    categories: ["Weekend", "2 Days", "Heritage"],
    coverImageLabel: "Ruins of the Vittala Temple complex, Hampi, golden hour",
    coverImage: "/photos/hampi-vittala-temple.jpg",
    gallery: ["Sunset at Matanga Hill", "Coracle ride on the Tungabhadra", "Group photo at the stone chariot"],
    description: [
      "A UNESCO World Heritage site that used to be one of the richest cities on earth, told by a local guide who treats it like a story instead of a syllabus.",
      "Boulders, temple ruins, a river crossing by coracle, and a sunset from Matanga Hill that photos genuinely undersell.",
    ],
    highlights: [
      "Guided walk through the Vittala Temple and the stone chariot",
      "Coracle ride across the Tungabhadra river",
      "Sunset from Matanga Hill",
    ],
    itinerary: [
      {
        day: 1,
        title: "Bengaluru to Hampi (overnight bus)",
        items: [
          { time: "21:00", label: "Board overnight bus from Bengaluru" },
        ],
      },
      {
        day: 2,
        title: "Hampi exploration",
        items: [
          { time: "06:00", label: "Arrive Hampi, freshen up" },
          { time: "08:00", label: "Breakfast" },
          { time: "09:00", label: "Guided heritage walk: Vittala Temple, stone chariot" },
          { time: "13:00", label: "Lunch (on your own)" },
          { time: "15:00", label: "Coracle ride" },
          { time: "18:00", label: "Sunset at Matanga Hill" },
          { time: "21:30", label: "Board return overnight bus" },
        ],
      },
    ],
    inclusions: ["AC overnight bus, both ways", "1 night guesthouse stay", "Breakfast Day 2", "Heritage guide", "Coracle ride"],
    exclusions: ["Lunch and dinner", "Monument entry tickets", "Personal expenses"],
    whoFor: ["History and heritage enthusiasts", "First-time group travellers", "Anyone new to Bengaluru wanting a low-effort weekend out"],
    faqs: [
      { question: "Is this trip beginner-friendly?", answer: "Yes — it involves walking on uneven, rocky terrain but no riding or trekking fitness required." },
      { question: "Do I need my own bike?", answer: "No, this trip travels by bus." },
      { question: "What should I carry?", answer: "Comfortable walking shoes, a hat, sunscreen and a water bottle — Hampi is hot and exposed for most of the day." },
    ],
    isSample: true,
  },
  {
    id: "t5",
    slug: "chikmagalur-weekday-escape",
    title: "Chikmagalur Weekday Escape",
    destination: "Chikmagalur, Karnataka",
    startingPoint: "Bengaluru",
    date: "Next batch — ask on WhatsApp",
    duration: "2 Days / 1 Night",
    transport: "Bike or Tempo Traveller",
    price: 5999,
    seatsTotal: 16,
    seatsLeft: 16,
    bookingStatus: "open",
    difficulty: "Moderate",
    stay: "Hillside homestay, twin sharing",
    food: "Breakfast and dinner included",
    categories: ["Weekday", "Nature", "Adventure"],
    coverImageLabel: "Mist over Mullayanagiri peak, Chikmagalur",
    coverImage: "/photos/chikmagalur-peak.jpg",
    gallery: ["Sunrise trek group at the peak", "Coffee estate breakfast table", "Homestay bonfire evening"],
    description: [
      "The trip for people whose weekends are already spoken for. Same planning, same small group, just on a Tuesday — and Chikmagalur without weekend traffic is a genuinely different, quieter place.",
      "A short peak trek, a coffee estate that isn't overrun, and a bonfire evening that doesn't feel rushed.",
    ],
    highlights: [
      "Mullayanagiri sunrise trek, Karnataka's highest peak",
      "A quiet, uncrowded coffee estate visit",
      "Weekday pricing and zero weekend traffic",
    ],
    itinerary: [
      {
        day: 1,
        title: "Bengaluru to Chikmagalur",
        items: [
          { time: "06:00", label: "Depart Bengaluru" },
          { time: "09:30", label: "Breakfast stop" },
          { time: "13:00", label: "Arrive, check in" },
          { time: "16:00", label: "Coffee estate visit" },
          { time: "20:00", label: "Dinner and bonfire" },
        ],
      },
      {
        day: 2,
        title: "Sunrise trek and return",
        items: [
          { time: "04:30", label: "Depart for Mullayanagiri" },
          { time: "06:00", label: "Sunrise at the peak" },
          { time: "09:00", label: "Breakfast" },
          { time: "11:00", label: "Depart for Bengaluru" },
          { time: "17:00", label: "Arrive Bengaluru" },
        ],
      },
    ],
    inclusions: ["Transport both ways (bike or Tempo, chosen at booking)", "1 night homestay", "Breakfast (both days) and Day 1 dinner", "Trek guide"],
    exclusions: ["Fuel (bike option)", "Lunch on both days", "Personal expenses"],
    whoFor: ["Anyone with flexible weekday leave", "Small groups wanting a quieter version of a popular destination", "Riders and non-riders alike — both transport options available"],
    faqs: [
      { question: "Do I need my own bike?", answer: "No — choose bike or Tempo Traveller when you book." },
      { question: "Is the trek difficult?", answer: "Moderate — around 90 minutes uphill, doable at a steady pace for most fitness levels." },
      { question: "Can I bring a friend?", answer: "Yes, book together or share a referral code." },
    ],
    isSample: true,
  },
  {
    id: "t6",
    slug: "munnar-tea-hills-long-weekend",
    title: "Munnar Tea Hills Long Weekend",
    destination: "Munnar, Kerala",
    startingPoint: "Bengaluru (Tempo Traveller pickup points shared after booking)",
    date: "Next batch — ask on WhatsApp",
    duration: "3 Days / 2 Nights",
    transport: "Tempo Traveller",
    price: 9499,
    seatsTotal: 14,
    seatsLeft: 14,
    bookingStatus: "open",
    difficulty: "Easy",
    stay: "Hillside resort/homestay, twin/triple sharing",
    food: "Breakfast and dinner included (both nights), lunch stops are pay-as-you-go",
    categories: ["Long Weekend", "Nature", "Trek"],
    coverImageLabel: "A waterfall cascading through a Munnar tea estate",
    coverImage: "/photos/munnar-tea-estate-falls.jpg",
    gallery: ["Tea garden walk", "Top Station viewpoint", "Group dinner at the homestay"],
    description: [
      "Endless tea gardens, a road that climbs through the clouds, and the kind of quiet you only get 1,600 metres up. Munnar is the trip for people who want green in every direction and no itinerary to plan themselves.",
      "Three days is enough to actually slow down — a tea estate walk, a viewpoint sunrise, and evenings that don't need an agenda.",
    ],
    highlights: [
      "Tea estate walk with a working plantation guide",
      "Top Station — the highest viewpoint on the Munnar-Kodaikanal road",
      "Two full days in the hills, not just a drive-through",
    ],
    itinerary: [
      {
        day: 1,
        title: "Bengaluru to Munnar",
        items: [
          { time: "06:00", label: "Depart Bengaluru" },
          { time: "09:30", label: "Breakfast stop" },
          { time: "17:00", label: "Arrive Munnar, check in" },
          { time: "20:00", label: "Group dinner at the homestay" },
        ],
      },
      {
        day: 2,
        title: "Tea gardens and Top Station",
        items: [
          { time: "07:00", label: "Breakfast" },
          { time: "08:30", label: "Tea estate walk and factory visit" },
          { time: "12:00", label: "Lunch (on your own)" },
          { time: "14:00", label: "Top Station viewpoint" },
          { time: "17:00", label: "Free evening in town" },
          { time: "20:00", label: "Dinner at the homestay" },
        ],
      },
      {
        day: 3,
        title: "Munnar to Bengaluru",
        items: [
          { time: "07:00", label: "Breakfast" },
          { time: "08:30", label: "Depart for Bengaluru" },
          { time: "13:00", label: "Lunch stop (on your own)" },
          { time: "20:00", label: "Arrive Bengaluru, trip ends" },
        ],
      },
    ],
    inclusions: [
      "Tempo Traveller transport both ways",
      "2 nights hillside stay, twin/triple sharing",
      "Breakfast and dinner (both nights)",
      "Tea estate walk and Top Station visit",
      "Trip WhatsApp group with live updates",
    ],
    exclusions: [
      "Lunch on all days",
      "Entry fees not part of the listed itinerary",
      "Personal expenses and shopping",
      "Anything not explicitly listed above",
    ],
    whoFor: [
      "Anyone who wants a proper long weekend out of the city without planning it",
      "Non-riders who still want the destination and the group",
      "Couples and friend groups after a slower-paced trip",
    ],
    faqs: [
      { question: "Do I need to ride a bike for this?", answer: "No — this trip uses a Tempo Traveller, no riding required." },
      { question: "How far is Munnar from Bengaluru?", answer: "Around 470 km — this is why it's a 3-day trip rather than a standard weekend." },
      { question: "Can I come alone?", answer: "Yes, solo travellers are common on our Tempo trips." },
      { question: "What's the cancellation policy?", answer: "Full details are on our Cancellation & Refund Policy page — in short, the earlier you cancel, the more you get back, and if Tripshala cancels a trip you get a full refund or a free move to another date." },
    ],
    isSample: true,
  },
  {
    id: "t7",
    slug: "kochi-alleppey-backwaters-getaway",
    title: "Kochi–Alleppey Backwaters Getaway",
    destination: "Kochi & Alleppey, Kerala",
    startingPoint: "Bengaluru (Tempo Traveller pickup points shared after booking)",
    date: "Next batch — ask on WhatsApp",
    duration: "3 Days / 2 Nights",
    transport: "Tempo Traveller",
    price: 10999,
    seatsTotal: 12,
    seatsLeft: 12,
    bookingStatus: "open",
    difficulty: "Easy",
    stay: "Fort Kochi heritage stay (Night 1) + houseboat on the Alleppey backwaters (Night 2)",
    food: "All meals included on the houseboat, breakfast included in Kochi",
    categories: ["Long Weekend", "Coastal", "Heritage"],
    coverImageLabel: "Houseboats moored along a tree-shaded Alleppey backwater canal",
    coverImage: "/photos/kochi-alleppey-backwaters-canal.jpg",
    gallery: ["Fort Kochi street art walk", "Houseboat deck at sunset", "Chinese fishing nets at dusk"],
    description: [
      "Two very different sides of Kerala in one trip — the old-world streets and cafés of Fort Kochi, then a night on a houseboat drifting through the Alleppey backwaters with nothing to do but watch the coconut palms go by.",
      "This is the trip we send people on when they want a proper switch-off, not another checklist of monuments.",
    ],
    highlights: [
      "A full night on a private houseboat, meals included",
      "Fort Kochi heritage walk — Chinese fishing nets, street art, old churches",
      "Backwater village stops most day-trippers never see",
    ],
    itinerary: [
      {
        day: 1,
        title: "Bengaluru to Kochi",
        items: [
          { time: "06:00", label: "Depart Bengaluru" },
          { time: "09:30", label: "Breakfast stop" },
          { time: "16:00", label: "Arrive Fort Kochi, check in" },
          { time: "17:30", label: "Fort Kochi heritage walk" },
          { time: "19:00", label: "Chinese fishing nets at sunset" },
        ],
      },
      {
        day: 2,
        title: "Kochi to Alleppey, board the houseboat",
        items: [
          { time: "08:00", label: "Breakfast, check out" },
          { time: "10:00", label: "Depart for Alleppey" },
          { time: "12:00", label: "Board the houseboat, welcome lunch" },
          { time: "14:00", label: "Backwater cruise through village stretches" },
          { time: "19:00", label: "Dinner on the houseboat, overnight on the water" },
        ],
      },
      {
        day: 3,
        title: "Alleppey to Bengaluru",
        items: [
          { time: "07:00", label: "Breakfast on the houseboat" },
          { time: "09:00", label: "Disembark, depart for Bengaluru" },
          { time: "13:00", label: "Lunch stop (on your own)" },
          { time: "21:00", label: "Arrive Bengaluru, trip ends" },
        ],
      },
    ],
    inclusions: [
      "Tempo Traveller transport both ways",
      "1 night Fort Kochi stay + 1 night private houseboat",
      "All meals on the houseboat, breakfast in Kochi",
      "Fort Kochi heritage walk",
      "Trip WhatsApp group with live updates",
    ],
    exclusions: [
      "Lunch on Day 1 and Day 3",
      "Monument/attraction entry fees",
      "Personal expenses and shopping",
      "Anything not explicitly listed above",
    ],
    whoFor: [
      "Anyone who wants a genuine switch-off weekend, not a sightseeing sprint",
      "Couples and friend groups celebrating something",
      "Non-riders who still want the trip planned end to end",
    ],
    faqs: [
      { question: "Do I need to ride a bike for this?", answer: "No — this trip uses a Tempo Traveller, no riding required." },
      { question: "Is the houseboat private to our group?", answer: "SAMPLE — confirm your actual houseboat-sharing arrangement (private vs shared) before launch." },
      { question: "Can I come alone?", answer: "Yes, solo travellers are welcome — you'll share the houseboat with the rest of the group." },
      { question: "What's the cancellation policy?", answer: "Full details are on our Cancellation & Refund Policy page — in short, the earlier you cancel, the more you get back, and if Tripshala cancels a trip you get a full refund or a free move to another date." },
    ],
    isSample: true,
  },
  {
    id: "t8",
    slug: "pondicherry-weekend-getaway",
    title: "Pondicherry Weekend Getaway",
    destination: "Puducherry",
    startingPoint: "Bengaluru",
    date: "Next batch — ask on WhatsApp",
    duration: "2 Days / 1 Night",
    transport: "Bus",
    price: 5999,
    seatsTotal: 25,
    seatsLeft: 25,
    bookingStatus: "open",
    difficulty: "Easy",
    stay: "French Quarter guesthouse, twin sharing",
    food: "Breakfast included, other meals on your own at local cafés",
    categories: ["Weekend", "Coastal", "Heritage"],
    coverImageLabel: "The golden Matrimandir dome at Auroville, near Pondicherry",
    coverImage: "/photos/pondicherry-auroville-dome.jpg",
    gallery: ["Promenade beach at sunrise", "French Quarter street walk", "Auroville viewpoint"],
    description: [
      "Cobbled streets, mustard-yellow colonial buildings, beachfront cafés and a completely different pace from anywhere else on the Tripshala map. Pondicherry is the weekend for people who want charm over adrenaline.",
      "An overnight bus down, a full day to wander the French Quarter and the promenade, and you're back in Bengaluru before Monday.",
    ],
    highlights: [
      "Guided walk through the French Quarter's colonial streets",
      "Sunrise at Promenade Beach",
      "A stop at Auroville's viewpoint",
    ],
    itinerary: [
      {
        day: 1,
        title: "Bengaluru to Pondicherry (overnight bus)",
        items: [
          { time: "22:00", label: "Board overnight bus from Bengaluru" },
        ],
      },
      {
        day: 2,
        title: "Pondicherry exploration",
        items: [
          { time: "06:00", label: "Arrive Pondicherry, freshen up" },
          { time: "07:00", label: "Sunrise at Promenade Beach" },
          { time: "08:30", label: "Breakfast" },
          { time: "10:00", label: "French Quarter heritage walk" },
          { time: "13:00", label: "Lunch (on your own)" },
          { time: "15:00", label: "Auroville viewpoint" },
          { time: "21:00", label: "Board return overnight bus" },
        ],
      },
    ],
    inclusions: [
      "AC overnight bus, both ways",
      "1 night French Quarter guesthouse stay",
      "Breakfast Day 2",
      "French Quarter heritage walk",
      "Trip WhatsApp group with live updates",
    ],
    exclusions: [
      "Lunch and dinner",
      "Auroville inner-circle entry (optional, on your own)",
      "Personal expenses",
    ],
    whoFor: [
      "First-time group travellers wanting a low-effort weekend out",
      "Anyone who prefers cafés and architecture over trekking",
      "Friend groups and couples",
    ],
    faqs: [
      { question: "Is this trip beginner-friendly?", answer: "Yes — it's mostly walking on flat, paved streets, no fitness requirements." },
      { question: "Do I need my own bike?", answer: "No, this trip travels by bus." },
      { question: "How far is Pondicherry from Bengaluru?", answer: "Around 320 km, roughly a 7-hour overnight drive." },
      { question: "What's the cancellation policy?", answer: "Full details are on our Cancellation & Refund Policy page — in short, the earlier you cancel, the more you get back, and if Tripshala cancels a trip you get a full refund or a free move to another date." },
    ],
    isSample: true,
  },
  {
    id: "t9",
    slug: "rameshwaram-island-temple-getaway",
    title: "Rameshwaram Island & Temple Getaway",
    destination: "Rameshwaram, Tamil Nadu",
    startingPoint: "Bengaluru",
    date: "Next batch — ask on WhatsApp",
    duration: "2 Days / 1 Night",
    transport: "Bus",
    price: 6999,
    seatsTotal: 25,
    seatsLeft: 25,
    bookingStatus: "open",
    difficulty: "Easy",
    stay: "Budget-comfort guesthouse near the temple, twin sharing (day-use, to freshen up between the overnight buses)",
    food: "Breakfast included, other meals on your own at local eateries",
    categories: ["Weekend", "2 Days", "Heritage", "Coastal", "Temple Trails"],
    coverImageLabel: "Pamban Bridge stretching out to sea toward Rameshwaram island",
    coverImage: "/photos/rameshwaram-pamban-bridge-aerial.jpg",
    gallery: [
      "Ramanathaswamy Temple's corridor at golden hour",
      "The ghost-town coastline at Dhanushkodi",
      "Sunrise over Agni Theertham beach",
    ],
    description: [
      "This is the farthest we send anyone, and the most unusual place on the Tripshala map — an island temple town where the Bay of Bengal and the Indian Ocean meet at the literal tip of India, and a coastline that still shows what a cyclone did to it in 1964.",
      "Two overnight buses bracket a single, full day on the ground: the 22-pillared corridor of the Ramanathaswamy Temple, the crossing over Pamban Bridge, and Dhanushkodi's abandoned shoreline — sand, ruins and sea in every direction, with almost nothing else built on it.",
    ],
    highlights: [
      "Ramanathaswamy Temple — the longest temple corridor in India, and the ritual bath across its 22 sacred wells",
      "Dhanushkodi's ghost-town coastline, abandoned after the 1964 cyclone and reachable only by van across the sand",
      "Crossing Pamban Bridge, India's first sea bridge linking the mainland to Rameshwaram island",
      "Arichal Munai, the sandy tip where the Bay of Bengal visibly meets the Indian Ocean",
    ],
    itinerary: [
      {
        day: 1,
        title: "Bengaluru to Rameshwaram (overnight bus)",
        items: [
          { time: "19:30", label: "Board overnight bus from Bengaluru" },
        ],
      },
      {
        day: 2,
        title: "Rameshwaram & Dhanushkodi",
        items: [
          { time: "06:30", label: "Arrive Rameshwaram, freshen up at the guesthouse" },
          { time: "08:00", label: "Breakfast" },
          { time: "09:00", label: "Ramanathaswamy Temple darshan (22 wells ritual bath optional — carry a spare set of dry clothes)" },
          { time: "11:30", label: "Pamban Bridge photo stop" },
          { time: "12:30", label: "Depart for Dhanushkodi by local van (the final stretch is sand-only, no private vehicles)" },
          { time: "13:30", label: "Dhanushkodi ghost town and Arichal Munai" },
          { time: "16:30", label: "Agni Theertham beach, free time" },
          { time: "19:00", label: "Dinner on your own, then head to the bus point" },
          { time: "21:00", label: "Board return overnight bus" },
        ],
      },
    ],
    inclusions: [
      "AC overnight bus, both ways",
      "1 night guesthouse (day-use, for freshening up)",
      "Breakfast Day 2",
      "Local van transfer to Dhanushkodi",
      "Trip WhatsApp group with live updates",
    ],
    exclusions: [
      "Lunch and dinner",
      "22 wells ritual bath fee (~₹25/person, paid on the spot) and cloakroom charges for phones/valuables",
      "Personal expenses and shopping",
      "Anything not explicitly listed above",
    ],
    whoFor: [
      "Anyone who wants a genuinely different landscape, not another hill station",
      "First-time group travellers up for a longer haul for a one-of-a-kind destination",
      "Photographers — Dhanushkodi's shipwreck coastline doesn't look like anywhere else on the map",
    ],
    faqs: [
      { question: "Is this trip beginner-friendly?", answer: "Yes — it's flat ground throughout (temple corridors, sand at Dhanushkodi), no trekking fitness needed. Expect strong sun and heat, so carry water and sun protection." },
      { question: "Do I need my own bike?", answer: "No, this trip travels by bus." },
      { question: "What's the dress code for the temple?", answer: "Ramanathaswamy Temple checks at every gate: men need a dhoti/veshti or formal trousers (no shorts or jeans), women need a saree, half-saree or salwar kameez with dupatta (no sleeveless tops, jeans or leggings)." },
      { question: "How far is Rameshwaram from Bengaluru?", answer: "Around 580-600 km by road — this is why it's built around two overnight buses rather than a same-day drive." },
      { question: "What's the cancellation policy?", answer: "Full details are on our Cancellation & Refund Policy page — in short, the earlier you cancel, the more you get back, and if Tripshala cancels a trip you get a full refund or a free move to another date." },
    ],
    isSample: true,
  },
  {
    id: "t10",
    slug: "manchanabele-lake-camping",
    title: "Manchanabele Lake Camping",
    destination: "Manchanabele, Karnataka",
    startingPoint: "Bengaluru (assembly point shared after booking)",
    date: "Next batch — ask on WhatsApp",
    duration: "Overnight (Saturday evening – Sunday morning)",
    transport: "Tempo Traveller",
    price: 2499,
    seatsTotal: 25,
    seatsLeft: 25,
    bookingStatus: "open",
    difficulty: "Easy",
    stay: "Twin/quad-sharing tents with sleeping bags, right by the water",
    food: "Evening snacks, bonfire dinner and breakfast included",
    categories: ["Camping", "Weekend", "Nature"],
    coverImageLabel: "Group photo by the Manchanabele reservoir under a monsoon sky",
    coverImage: "/photos/community-lake-group.jpg",
    gallery: [
      "Tents pitched right at the water's edge",
      "Bonfire circle after dinner",
      "Kayaking on the reservoir at sunrise",
    ],
    description: [
      "Forty kilometres from the city and it already feels like a different state of mind — a reservoir ringed by hills, tents up before sunset, and a bonfire that runs long after dinner.",
      "This is the trip for people who want the campfire-and-stars evening without giving up their whole weekend to get there. No early alarm, no long drive — just leave Saturday afternoon and you're back well before lunch on Sunday.",
    ],
    highlights: [
      "Camp right on the edge of the Manchanabele reservoir",
      "Bonfire dinner and a night under genuinely dark skies",
      "Sunrise kayaking session included, no extra cost",
      "Closest overnight escape from Bengaluru — barely a 90-minute drive",
    ],
    itinerary: [
      {
        day: 1,
        title: "Bengaluru to Manchanabele, camp setup",
        items: [
          { time: "15:00", label: "Assemble at the pickup point" },
          { time: "15:30", label: "Depart Bengaluru" },
          { time: "17:00", label: "Arrive at the campsite, tents set up" },
          { time: "18:30", label: "Evening snacks and tea by the water" },
          { time: "20:00", label: "Bonfire dinner and games" },
          { time: "22:30", label: "Lights out (or stay up and watch the stars)" },
        ],
      },
      {
        day: 2,
        title: "Sunrise, kayaking and return",
        items: [
          { time: "06:30", label: "Sunrise by the reservoir" },
          { time: "07:00", label: "Kayaking session" },
          { time: "08:30", label: "Breakfast" },
          { time: "10:00", label: "Pack up and depart" },
          { time: "11:30", label: "Arrive back in Bengaluru, trip ends" },
        ],
      },
    ],
    inclusions: [
      "Tempo Traveller pickup and drop from Bengaluru",
      "Tent and sleeping bag, twin/quad sharing",
      "Evening snacks, bonfire dinner and breakfast",
      "Sunrise kayaking session",
      "Trip WhatsApp group with live updates",
    ],
    exclusions: [
      "Lunch",
      "Any water sport beyond the included kayaking session",
      "Personal expenses and shopping",
      "Anything not explicitly listed above",
    ],
    whoFor: [
      "First-time campers who don't want to buy gear before trying it",
      "Small groups of friends wanting an easy overnight escape",
      "Anyone who wants Saturday night away without losing all of Sunday",
    ],
    faqs: [
      { question: "Do I need my own camping gear?", answer: "No — tents, sleeping bags and the campsite setup are all handled. Just bring a change of clothes and any personal essentials." },
      { question: "What if it rains?", answer: "We monitor the forecast closely; if conditions turn unsafe for tent camping, we move the group to a covered stay nearby and let everyone know in advance." },
      { question: "Can I drive myself instead of taking the Tempo Traveller?", answer: "Yes, self-drive is possible — message us on WhatsApp after booking for the exact campsite location and timing." },
    ],
    isSample: true,
  },
  {
    id: "t11",
    slug: "kabini-wildlife-safari-weekend",
    title: "Kabini Wildlife Safari Weekend",
    destination: "Kabini (Nagarhole), Karnataka",
    startingPoint: "Bengaluru (Tempo Traveller pickup points shared after booking)",
    date: "Next batch — ask on WhatsApp",
    duration: "2 Days / 1 Night",
    transport: "Tempo Traveller",
    price: 7999,
    seatsTotal: 20,
    seatsLeft: 20,
    bookingStatus: "open",
    difficulty: "Easy",
    stay: "Resort/homestay near the Kabini backwaters, twin sharing",
    food: "Breakfast and dinner included, lunch stops are pay-as-you-go",
    categories: ["Wildlife", "Weekend", "2 Days", "Nature"],
    coverImageLabel: "Safari jeeps lined up at the forest gate at first light",
    coverImage: "/photos/gallery-jeep-safari.jpg",
    gallery: [
      "Elephant herd at the Kabini backwaters",
      "Group before the evening safari",
      "Coracle ride at sunset",
    ],
    description: [
      "Kabini is routinely rated among the best wildlife destinations in India — elephant herds by the hundreds in season, real odds of a leopard sighting, and backwaters that turn gold at sunset.",
      "Two jeep safaris with a trained naturalist, a night by the water, and a genuinely wild weekend without needing to fly anywhere or plan a thing yourself.",
    ],
    highlights: [
      "Two jungle safaris (dawn and dusk) with a naturalist",
      "Among the best leopard and elephant sighting odds in South India",
      "Sunset coracle ride on the Kabini backwaters",
      "Small group, twin-sharing stay a short drive from the reserve",
    ],
    itinerary: [
      {
        day: 1,
        title: "Bengaluru to Kabini, evening safari",
        items: [
          { time: "05:30", label: "Assemble at the pickup point" },
          { time: "06:00", label: "Depart Bengaluru" },
          { time: "11:30", label: "Arrive Kabini, check in" },
          { time: "13:00", label: "Lunch (on your own)" },
          { time: "15:30", label: "Evening jungle safari" },
          { time: "20:00", label: "Dinner" },
        ],
      },
      {
        day: 2,
        title: "Dawn safari, backwaters and return",
        items: [
          { time: "06:00", label: "Dawn jungle safari" },
          { time: "09:00", label: "Breakfast" },
          { time: "10:30", label: "Coracle ride on the backwaters" },
          { time: "12:00", label: "Check out, depart for Bengaluru" },
          { time: "18:00", label: "Arrive Bengaluru, trip ends" },
        ],
      },
    ],
    inclusions: [
      "Tempo Traveller pickup and drop from Bengaluru",
      "2 jungle safaris with naturalist and park entry fees",
      "1 night stay, twin sharing",
      "Breakfast and dinner",
      "Coracle ride on the backwaters",
      "Trip WhatsApp group with live updates",
    ],
    exclusions: [
      "Lunch on both days",
      "Camera/video fees at the safari gate, if applicable",
      "Personal expenses and shopping",
      "Anything not explicitly listed above",
    ],
    whoFor: [
      "Wildlife and nature lovers",
      "Photographers chasing genuinely good sighting odds",
      "Anyone who wants a wild weekend without a flight",
    ],
    faqs: [
      { question: "Are sightings guaranteed?", answer: "No wildlife sighting can ever be guaranteed, but Kabini is consistently ranked among the best in India for leopard and elephant sightings, especially in the dry months." },
      { question: "What should I carry?", answer: "Neutral-coloured clothing, a cap, and binoculars or a zoom lens if you have one. Safaris run rain or shine." },
      { question: "Are safari timings fixed?", answer: "Yes, safari slots are set by the forest department and can shift slightly by season — the final timing is confirmed on the trip WhatsApp group." },
    ],
    isSample: true,
  },
  {
    id: "t12",
    slug: "savandurga-sunrise-trek",
    title: "Savandurga Sunrise Trek",
    destination: "Savandurga, Karnataka",
    startingPoint: "Bengaluru (assembly point shared after booking)",
    date: "Next batch — ask on WhatsApp",
    duration: "One day (5-6 hours round trip)",
    transport: "Tempo Traveller",
    price: 1299,
    seatsTotal: 20,
    seatsLeft: 20,
    bookingStatus: "open",
    difficulty: "Moderate",
    stay: "Not applicable — same-day return",
    food: "Breakfast included, carry your own water",
    categories: ["One Day", "Trek", "Adventure", "Nature"],
    coverImageLabel: "Group at the base of the Savandurga monolith",
    coverImage: "/photos/hero-riders-savandurga.jpg",
    gallery: [
      "Climbing the exposed granite face",
      "View of the Manchanabele reservoir from the top",
      "Group breakfast at the base",
    ],
    description: [
      "Savandurga is one of the largest monolith hills in Asia, and the climb up its bare granite face is the closest thing to real exposure you'll find on a one-day trip out of Bengaluru.",
      "Fort ruins, temple stops, and views of three reservoirs from the top — all wrapped into a single day that still gets you home for dinner.",
    ],
    highlights: [
      "One of the largest monolith rock formations in Asia",
      "Views of the Manchanabele, Thippagondanahalli and Magadi reservoirs",
      "Historic Savandurga fort and temple ruins en route",
      "Beginner-friendly but with genuine elevation and exposed rock",
    ],
    itinerary: [
      {
        day: 1,
        title: "Savandurga day trek",
        items: [
          { time: "05:00", label: "Assemble at the pickup point" },
          { time: "05:30", label: "Depart Bengaluru" },
          { time: "07:00", label: "Arrive base, breakfast" },
          { time: "07:45", label: "Start the climb" },
          { time: "10:00", label: "Reach the summit, break" },
          { time: "11:00", label: "Begin descent" },
          { time: "13:00", label: "Back at the base, depart for Bengaluru" },
          { time: "14:30", label: "Arrive Bengaluru, trip ends" },
        ],
      },
    ],
    inclusions: [
      "Tempo Traveller pickup and drop from Bengaluru",
      "Breakfast",
      "Trek lead and sweep guide",
      "Trip WhatsApp group with live updates",
    ],
    exclusions: [
      "Lunch",
      "Entry/parking fee, if applicable, paid on the spot",
      "Personal expenses and shopping",
      "Anything not explicitly listed above",
    ],
    whoFor: [
      "First-time trekkers wanting real elevation without an overnight commitment",
      "Weekend warriors looking for a half-day workout with a view",
      "Photographers — the granite face and reservoir views are worth the climb",
    ],
    faqs: [
      { question: "How difficult is this trek?", answer: "Moderate — around 4 hours of active trekking with some exposed granite sections. Reasonable fitness is needed, but no prior trekking experience." },
      { question: "What footwear should I wear?", answer: "Trekking or sports shoes with good grip — the granite gets slippery, especially if there's any dew or recent rain." },
      { question: "Is this suitable for kids?", answer: "Not recommended for children under 12 given the steep, exposed sections near the top." },
    ],
    isSample: true,
  },
  {
    id: "t13",
    slug: "skandagiri-night-trek",
    title: "Skandagiri Night Trek & Sunrise",
    destination: "Skandagiri, Karnataka",
    startingPoint: "Bengaluru (assembly point shared after booking)",
    date: "Next batch — ask on WhatsApp",
    duration: "Overnight (11pm start, back by 9am)",
    transport: "Tempo Traveller",
    price: 999,
    seatsTotal: 25,
    seatsLeft: 25,
    bookingStatus: "open",
    difficulty: "Moderate",
    stay: "Not applicable — overnight trek, no stay",
    food: "Hot tea/coffee at the summit; breakfast on the way back is on your own",
    categories: ["One Day", "Trek", "Adventure", "Nature"],
    coverImageLabel: "Trekkers climbing through cloud cover on the way to Skandagiri's summit",
    coverImage: "/photos/gallery-foggy-trek.jpg",
    gallery: [
      "Climbing above the cloud line before dawn",
      "Fort ruins at the summit",
      "Sea of clouds at sunrise",
    ],
    description: [
      "Skandagiri's claim to fame is the 'sea of clouds' — a blanket of fog sitting in the valley below while the summit stays clear, visible only if you're up there before the sun is.",
      "That means a late-night start, a climb under the stars, and a sunrise most people only see in photos. You're back in the city well before your Sunday would normally even start.",
    ],
    highlights: [
      "The famous sea-of-clouds view at sunrise (best in the winter months)",
      "A night trek under genuinely dark, star-filled skies",
      "Fort ruins at the summit to explore while you wait for first light",
      "Back home by mid-morning, the rest of Sunday still free",
    ],
    itinerary: [
      {
        day: 1,
        title: "Night trek and sunrise",
        items: [
          { time: "23:00", label: "Assemble at the pickup point" },
          { time: "23:30", label: "Depart Bengaluru" },
          { time: "01:30", label: "Reach the base, start the climb" },
          { time: "04:00", label: "Reach the summit, hot tea/coffee" },
          { time: "06:00", label: "Sunrise over the sea of clouds" },
          { time: "07:00", label: "Begin descent" },
          { time: "08:30", label: "Depart for Bengaluru" },
          { time: "09:30", label: "Arrive Bengaluru, trip ends" },
        ],
      },
    ],
    inclusions: [
      "Tempo Traveller pickup and drop from Bengaluru",
      "Trek lead and sweep guide with torches and first-aid",
      "Hot tea/coffee at the summit",
      "Trip WhatsApp group with live updates",
    ],
    exclusions: [
      "Dinner before the trek",
      "Breakfast on the way back",
      "Personal expenses and shopping",
      "Anything not explicitly listed above",
    ],
    whoFor: [
      "Anyone chasing the sea-of-clouds view without an overnight stay",
      "First-time night trekkers — the route is easy to follow with a lead and sweep guide",
      "People who want a big Saturday-night adventure and their whole Sunday back",
    ],
    faqs: [
      { question: "Is a night trek safe?", answer: "Yes — the group always moves together with a lead and sweep guide, torches, and a first-aid kit, on a well-marked route." },
      { question: "What should I carry?", answer: "A torch or headlamp, a warm layer (it gets cold at the top), and at least 1 litre of water." },
      { question: "How fit do I need to be?", answer: "Moderate fitness is enough — roughly 2 hours of climbing at a steady pace, done in the cool of the night rather than daytime heat." },
    ],
    isSample: true,
  },
  {
    id: "t14",
    slug: "lepakshi-temple-day-trip",
    title: "Lepakshi Temple Day Trip",
    destination: "Lepakshi, Andhra Pradesh (just across the Karnataka border)",
    startingPoint: "Bengaluru (assembly point shared after booking)",
    date: "Next batch — ask on WhatsApp",
    duration: "One day (7-8 hours round trip)",
    transport: "Tempo Traveller",
    price: 1199,
    seatsTotal: 25,
    seatsLeft: 25,
    bookingStatus: "open",
    difficulty: "Easy",
    stay: "N/A — same-day trip, no overnight stay",
    food: "Tea/breakfast stop and lunch on your own at local eateries",
    categories: ["Temple Trails", "One Day", "Heritage"],
    coverImageLabel: "The Nagalinga — a multi-hooded stone serpent shrine — at Lepakshi temple",
    coverImage: "/photos/lepakshi-nagalinga.jpg",
    gallery: [
      "The famous hanging pillar inside the main mandapa",
      "Vijayanagara-era ceiling frescoes",
      "The unfinished Kalyana Mandapa",
    ],
    description: [
      "Lepakshi is the easiest genuinely spectacular day trip out of Bengaluru — a 16th-century Vijayanagara-era temple town barely two hours away, built by two brothers who served under Achutaraya, and packed with the kind of craftsmanship you usually have to travel much further to see.",
      "The Veerabhadra Temple's ceiling frescoes are some of the best-preserved in South India, the giant monolithic Nandi outside is one of the largest in the country, and the temple's 'hanging pillar' — one of 70 pillars that doesn't actually touch the ground — is the thing everyone comes to see for themselves.",
    ],
    highlights: [
      "The hanging pillar — slide something under it and watch it pass clean through",
      "One of India's largest monolithic Nandi statues, carved from a single granite boulder",
      "Vijayanagara-era ceiling frescoes in vivid, original colour",
      "The unfinished Kalyana Mandapa and its giant carved granite pillars",
    ],
    itinerary: [
      {
        day: 1,
        title: "Bengaluru – Lepakshi – Bengaluru",
        items: [
          { time: "06:00", label: "Assemble at the pickup point" },
          { time: "06:30", label: "Depart Bengaluru" },
          { time: "09:00", label: "Breakfast stop en route" },
          { time: "10:30", label: "Arrive Lepakshi, Veerabhadra Temple guided walk" },
          { time: "12:30", label: "Monolithic Nandi and Kalyana Mandapa" },
          { time: "13:30", label: "Lunch (on your own)" },
          { time: "14:30", label: "Depart for Bengaluru" },
          { time: "17:30", label: "Arrive Bengaluru, trip ends" },
        ],
      },
    ],
    inclusions: [
      "AC Tempo Traveller pickup and drop from Bengaluru",
      "Guided walk through the temple complex",
      "Trip WhatsApp group with live updates",
    ],
    exclusions: [
      "Breakfast and lunch",
      "Temple donations or special darshan fees, if any",
      "Personal expenses and shopping",
      "Anything not explicitly listed above",
    ],
    whoFor: [
      "First-timers who want a big, genuinely impressive day trip without committing a whole weekend",
      "Anyone into temple architecture, frescoes or history",
      "Families and slow-paced groups — there's no trekking or physical strain involved",
    ],
    faqs: [
      { question: "Is this trip beginner-friendly?", answer: "Yes — it's flat ground throughout with some walking around the temple complex, no fitness requirement at all." },
      { question: "How far is Lepakshi from Bengaluru?", answer: "Around 120km, roughly 2-2.5 hours each way." },
      { question: "Is there a dress code?", answer: "Standard modest temple dress — covered shoulders and knees. No strict dhoti/saree requirement like some larger pilgrimage temples." },
      { question: "What's the cancellation policy?", answer: "Full details are on our Cancellation & Refund Policy page — in short, the earlier you cancel, the more you get back, and if Tripshala cancels a trip you get a full refund or a free move to another date." },
    ],
    isSample: true,
  },
  {
    id: "t15",
    slug: "melkote-temple-trail",
    title: "Melkote Temple Trail",
    destination: "Melkote, Karnataka",
    startingPoint: "Bengaluru (assembly point shared after booking)",
    date: "Next batch — ask on WhatsApp",
    duration: "One day (7-8 hours round trip)",
    transport: "Tempo Traveller",
    price: 1299,
    seatsTotal: 25,
    seatsLeft: 25,
    bookingStatus: "open",
    difficulty: "Easy",
    stay: "N/A — same-day trip, no overnight stay",
    food: "Tea/breakfast stop and lunch on your own at local eateries",
    categories: ["Temple Trails", "One Day", "Heritage"],
    coverImageLabel: "The stepped Kalyani tank at Melkote, with the hilltop temple beyond",
    coverImage: "/photos/melkote-kalyani-tank.jpg",
    gallery: [
      "The Kalyani stepped tank at Cheluvanarayana Swamy Temple",
      "Steps leading up to the Yoganarasimha Temple",
      "Panoramic view over the Melkote hills",
    ],
    description: [
      "Melkote is a quieter kind of pilgrimage town — a hilltop settlement in Mandya district closely tied to the Sri Vaishnava saint Ramanujacharya, who lived here for years, and still one of the least touristy temple destinations within easy reach of Bengaluru.",
      "The plan is simple: the Cheluvanarayana Swamy Temple and its striking stepped Kalyani tank down in the town, then a climb up to the Yoganarasimha Temple on the hill above for one of the best 360-degree views in the region.",
    ],
    highlights: [
      "Cheluvanarayana Swamy Temple and the ornate stepped Kalyani tank",
      "The climb up to Yoganarasimha Temple for panoramic hill views",
      "A genuinely uncrowded pilgrimage town, even on weekends",
      "Strong Ramanujacharya history for anyone into temple history",
    ],
    itinerary: [
      {
        day: 1,
        title: "Bengaluru – Melkote – Bengaluru",
        items: [
          { time: "06:00", label: "Assemble at the pickup point" },
          { time: "06:30", label: "Depart Bengaluru" },
          { time: "09:30", label: "Breakfast stop en route" },
          { time: "10:30", label: "Arrive Melkote, Cheluvanarayana Swamy Temple and Kalyani tank" },
          { time: "12:00", label: "Climb to Yoganarasimha Temple" },
          { time: "13:30", label: "Lunch (on your own)" },
          { time: "14:30", label: "Depart for Bengaluru" },
          { time: "18:00", label: "Arrive Bengaluru, trip ends" },
        ],
      },
    ],
    inclusions: [
      "AC Tempo Traveller pickup and drop from Bengaluru",
      "Trip WhatsApp group with live updates",
    ],
    exclusions: [
      "Breakfast and lunch",
      "Temple donations or special darshan fees, if any",
      "Personal expenses and shopping",
      "Anything not explicitly listed above",
    ],
    whoFor: [
      "Anyone who wants a quieter, less commercial temple town",
      "Slow-travel and history-minded folks",
      "First-time group travellers looking for an easy day out",
    ],
    faqs: [
      { question: "Is this trip beginner-friendly?", answer: "Yes, though the climb up to Yoganarasimha Temple involves a flight of steps — moderate fitness is enough." },
      { question: "How far is Melkote from Bengaluru?", answer: "Around 145km via Mandya, roughly 3 hours each way." },
      { question: "Is there a dress code?", answer: "Standard modest temple dress — covered shoulders and knees." },
      { question: "What's the cancellation policy?", answer: "Full details are on our Cancellation & Refund Policy page — in short, the earlier you cancel, the more you get back, and if Tripshala cancels a trip you get a full refund or a free move to another date." },
    ],
    isSample: true,
  },
  {
    id: "t16",
    slug: "talakadu-shivanasamudra-temple-trail",
    title: "Talakadu Sand Temples & Shivanasamudra Falls",
    destination: "Talakadu & Shivanasamudra, Karnataka",
    startingPoint: "Bengaluru (assembly point shared after booking)",
    date: "Next batch — ask on WhatsApp",
    duration: "One day (8-9 hours round trip)",
    transport: "Tempo Traveller",
    price: 1399,
    seatsTotal: 25,
    seatsLeft: 25,
    bookingStatus: "open",
    difficulty: "Easy",
    stay: "N/A — same-day trip, no overnight stay",
    food: "Tea/breakfast stop and lunch on your own at local eateries",
    categories: ["Temple Trails", "One Day", "Heritage", "Nature"],
    coverImageLabel: "Vaidyeshwara Temple half-buried in river sand at Talakadu",
    coverImage: "/photos/talakadu-sand-temple.jpg",
    gallery: [
      "The Kaveri riverbank at Talakadu",
      "Gaganachukki falls at Shivanasamudra",
      "Sand dunes surrounding the Panchalinga temples",
    ],
    description: [
      "Talakadu is one of the stranger, more atmospheric temple sites near Bengaluru — a former temple town on the banks of the Kaveri that got buried under sand dunes centuries ago, according to legend after a curse, and is only fully uncovered once every 12 years for the Panchalinga Darshana festival.",
      "We pair it with Shivanasamudra, twenty-odd kilometres away — twin waterfalls (Gaganachukki and Barachukki) on the same river, and one of the better nature stops within day-trip range of the city.",
    ],
    highlights: [
      "Vaidyeshwara Temple and the sand-buried Panchalinga temple sites",
      "A walk along the Kaveri riverbank at Talakadu",
      "Gaganachukki and Barachukki waterfalls at Shivanasamudra",
      "A genuinely different landscape — sand dunes on a riverbank, unlike anywhere else nearby",
    ],
    itinerary: [
      {
        day: 1,
        title: "Bengaluru – Talakadu – Shivanasamudra – Bengaluru",
        items: [
          { time: "06:00", label: "Assemble at the pickup point" },
          { time: "06:30", label: "Depart Bengaluru" },
          { time: "09:30", label: "Breakfast stop en route" },
          { time: "10:30", label: "Arrive Talakadu, temple walk and riverbank" },
          { time: "12:30", label: "Depart for Shivanasamudra" },
          { time: "13:15", label: "Lunch (on your own)" },
          { time: "14:00", label: "Gaganachukki and Barachukki falls viewpoints" },
          { time: "15:30", label: "Depart for Bengaluru" },
          { time: "19:00", label: "Arrive Bengaluru, trip ends" },
        ],
      },
    ],
    inclusions: [
      "AC Tempo Traveller pickup and drop from Bengaluru",
      "Trip WhatsApp group with live updates",
    ],
    exclusions: [
      "Breakfast and lunch",
      "Temple donations, if any",
      "Personal expenses and shopping",
      "Anything not explicitly listed above",
    ],
    whoFor: [
      "Anyone who wants temple history and nature in the same day",
      "Photographers — the sand-buried temples and the falls are both very visual",
      "First-time group travellers looking for an easy, well-rounded day out",
    ],
    faqs: [
      { question: "Is this trip beginner-friendly?", answer: "Yes, it's mostly flat walking at both stops — no fitness requirement." },
      { question: "How far is Talakadu from Bengaluru?", answer: "Around 135km, roughly 3 hours each way; Shivanasamudra is a further 20-odd km from Talakadu." },
      { question: "Can we get close to the waterfalls?", answer: "You'll view them from marked viewpoints — getting into the water is restricted and unsafe at both falls, and we stick to the safe viewing areas." },
      { question: "What's the cancellation policy?", answer: "Full details are on our Cancellation & Refund Policy page — in short, the earlier you cancel, the more you get back, and if Tripshala cancels a trip you get a full refund or a free move to another date." },
    ],
    isSample: true,
  },
  {
    id: "t17",
    slug: "nanjangud-mysore-temple-trail",
    title: "Nanjangud & Chamundi Hill Temple Trail",
    destination: "Nanjangud & Mysuru, Karnataka",
    startingPoint: "Bengaluru (assembly point shared after booking)",
    date: "Next batch — ask on WhatsApp",
    duration: "One day (9-10 hours round trip)",
    transport: "Tempo Traveller",
    price: 1499,
    seatsTotal: 25,
    seatsLeft: 25,
    bookingStatus: "open",
    difficulty: "Easy",
    stay: "N/A — same-day trip, no overnight stay",
    food: "Tea/breakfast stop and lunch on your own at local eateries",
    categories: ["Temple Trails", "One Day", "Heritage"],
    coverImageLabel: "Chamundeshwari Temple atop Chamundi Hill overlooking Mysuru",
    coverImage: "/photos/chamundi-hill-temple.jpg",
    gallery: [
      "Srikanteshwara Temple's tall gopura at Nanjangud",
      "The giant Nandi statue and steps up Chamundi Hill",
      "View over Mysuru city from Chamundi Hill",
    ],
    description: [
      "This one covers two of Karnataka's biggest active temples in a single long day — Srikanteshwara Temple in Nanjangud, one of the largest temple complexes in the state and known locally as 'Dakshina Kashi' (the Varanasi of the South), and Chamundeshwari Temple on Chamundi Hill above Mysuru, the presiding deity of the old Mysore royal family.",
      "It's a longer day than our other temple trails, but the payoff is real: two major pilgrimage sites and a proper hilltop view over Mysuru, all without an overnight stay.",
    ],
    highlights: [
      "Srikanteshwara Temple — one of Karnataka's largest temple complexes, on the banks of the Kapila river",
      "Chamundeshwari Temple atop Chamundi Hill, seat of the Mysore royal family's deity",
      "The giant Nandi statue partway up Chamundi Hill",
      "Panoramic views over Mysuru city from the hilltop",
    ],
    itinerary: [
      {
        day: 1,
        title: "Bengaluru – Nanjangud – Chamundi Hill – Bengaluru",
        items: [
          { time: "05:30", label: "Assemble at the pickup point" },
          { time: "06:00", label: "Depart Bengaluru" },
          { time: "08:30", label: "Breakfast stop en route" },
          { time: "10:00", label: "Arrive Nanjangud, Srikanteshwara Temple" },
          { time: "12:00", label: "Depart for Chamundi Hill" },
          { time: "13:00", label: "Lunch (on your own) near Mysuru" },
          { time: "14:00", label: "Chamundeshwari Temple and Chamundi Hill viewpoint" },
          { time: "16:00", label: "Depart for Bengaluru" },
          { time: "19:30", label: "Arrive Bengaluru, trip ends" },
        ],
      },
    ],
    inclusions: [
      "AC Tempo Traveller pickup and drop from Bengaluru",
      "Trip WhatsApp group with live updates",
    ],
    exclusions: [
      "Breakfast and lunch",
      "Temple donations or special darshan fees, if any",
      "Personal expenses and shopping",
      "Anything not explicitly listed above",
    ],
    whoFor: [
      "Anyone who wants two major temples covered in one trip",
      "First-time group travellers comfortable with a longer day out",
      "Families — both stops are easy walking, no trekking involved",
    ],
    faqs: [
      { question: "Is this a long day?", answer: "Yes, it's our longest single-day temple trip at roughly 9-10 hours round trip including both stops — worth it for covering two major temples, but let us know if you'd prefer to split it into two separate trips instead." },
      { question: "How far is Nanjangud from Bengaluru?", answer: "Around 150km; Chamundi Hill near Mysuru is a further 25km or so from Nanjangud." },
      { question: "Is there a dress code?", answer: "Standard modest temple dress — covered shoulders and knees." },
      { question: "What's the cancellation policy?", answer: "Full details are on our Cancellation & Refund Policy page — in short, the earlier you cancel, the more you get back, and if Tripshala cancels a trip you get a full refund or a free move to another date." },
    ],
    isSample: true,
  },
  {
    id: "t18",
    slug: "sringeri-horanadu-kalasa-temple-circuit",
    title: "Sringeri – Horanadu – Kalasa Temple Circuit",
    destination: "Chikkamagaluru district, Karnataka",
    startingPoint: "Bengaluru (assembly point shared after booking)",
    date: "Next batch — ask on WhatsApp",
    duration: "2 Days / 1 Night (Friday night departure, back Sunday night)",
    transport: "Tempo Traveller",
    price: 6999,
    seatsTotal: 20,
    seatsLeft: 20,
    bookingStatus: "open",
    difficulty: "Easy",
    stay: "Guesthouse/homestay near Horanadu or Kalasa, twin sharing",
    food: "Breakfast both days included; free temple prasadam lunch at Horanadu; dinner and Day 2 lunch on your own",
    categories: ["Temple Trails", "Weekend", "2 Days", "Heritage"],
    coverImageLabel: "The Sharada Peetham temple complex at Sringeri on the Tunga river",
    coverImage: "/photos/sringeri-sharada-temple.jpg",
    gallery: [
      "Vidyashankara Temple at Sringeri at sunrise",
      "Annapoorneshwari Temple at Horanadu",
      "The Bhadra river at Kalasa",
    ],
    description: [
      "This is our full temple weekend — three of Karnataka's most important pilgrimage sites, all within the same forested pocket of the Western Ghats in Chikkamagaluru district: Sringeri, seat of the Sharada Peetham founded by Adi Shankara; Horanadu, home to the Annapoorneshwari Temple and its famous free community lunch; and Kalasa, a quieter riverside temple town on the Bhadra.",
      "It's a genuine overnight haul to get out here, which is exactly why most people never do all three in one trip — we've built the whole weekend around it so you don't have to plan a thing.",
    ],
    highlights: [
      "Sharada Peetham and Vidyashankara Temple at Sringeri, on the banks of the Tunga",
      "Annapoorneshwari Temple at Horanadu, including its free community prasadam lunch",
      "Kalaseshwara Temple at Kalasa on the Bhadra river",
      "A genuinely offbeat Western Ghats temple circuit, well outside the usual weekend crowd",
    ],
    itinerary: [
      {
        day: 1,
        title: "Overnight departure, Sringeri and Horanadu",
        items: [
          { time: "22:00", label: "Depart Bengaluru (Friday night)" },
          { time: "05:30", label: "Arrive Sringeri, freshen up" },
          { time: "07:00", label: "Sharada Peetham and Vidyashankara Temple darshan" },
          { time: "09:00", label: "Breakfast" },
          { time: "10:30", label: "Depart for Horanadu" },
          { time: "12:30", label: "Annapoorneshwari Temple darshan and community prasadam lunch" },
          { time: "14:30", label: "Depart for Kalasa" },
          { time: "15:30", label: "Kalaseshwara Temple and the Bhadra riverbank" },
          { time: "17:00", label: "Check in, evening at leisure" },
          { time: "19:30", label: "Dinner (on your own)" },
        ],
      },
      {
        day: 2,
        title: "Leisure morning and return",
        items: [
          { time: "08:00", label: "Breakfast" },
          { time: "09:00", label: "Optional visit to Hebbe Falls area (subject to time and road conditions)" },
          { time: "12:00", label: "Check out, depart for Bengaluru" },
          { time: "20:30", label: "Arrive Bengaluru, trip ends" },
        ],
      },
    ],
    inclusions: [
      "AC Tempo Traveller pickup and drop from Bengaluru",
      "1 night stay, twin sharing",
      "Breakfast both days",
      "Community prasadam lunch at Horanadu",
      "Trip WhatsApp group with live updates",
    ],
    exclusions: [
      "Dinner Day 1 and lunch Day 2",
      "Temple donations or special darshan fees, if any",
      "Personal expenses and shopping",
      "Anything not explicitly listed above",
    ],
    whoFor: [
      "Anyone who wants a proper temple pilgrimage weekend, not just a day trip",
      "First-time group travellers okay with an overnight journey out and back",
      "Photographers and Western Ghats fans — this route is genuinely scenic, not just about the temples",
    ],
    faqs: [
      { question: "Is this trip beginner-friendly?", answer: "Yes — all three temple stops involve normal walking, no trekking. The main thing to plan around is the overnight travel both ways." },
      { question: "How far is Sringeri from Bengaluru?", answer: "Around 330km, roughly 7-8 hours by road, which is why we travel overnight on Friday to make the most of Saturday and Sunday." },
      { question: "Is the Horanadu lunch really free?", answer: "Yes — Annapoorneshwari Temple runs a free community lunch (annadanam) for all visitors, a genuine highlight of the trip." },
      { question: "What's the cancellation policy?", answer: "Full details are on our Cancellation & Refund Policy page — in short, the earlier you cancel, the more you get back, and if Tripshala cancels a trip you get a full refund or a free move to another date." },
    ],
    isSample: true,
  },
  {
    id: "t19",
    slug: "tirupati-balaji-weekend-darshan",
    title: "Tirupati Balaji Weekend Darshan",
    destination: "Tirumala, Andhra Pradesh",
    startingPoint: "Bengaluru (assembly point shared after booking)",
    date: "Next batch — ask on WhatsApp",
    duration: "2 Days / 1 Night (Friday night departure, back Sunday night)",
    transport: "Tempo Traveller",
    price: 6499,
    seatsTotal: 20,
    seatsLeft: 20,
    bookingStatus: "open",
    difficulty: "Easy",
    stay: "Guesthouse/lodge near Tirumala or Tirupati town, twin sharing",
    food: "Breakfast both days included, other meals on your own",
    categories: ["Temple Trails", "Weekend", "2 Days", "Heritage"],
    coverImageLabel: "The gopuram of the Sri Venkateswara Temple complex at Tirumala",
    coverImage: "/photos/tirupati-tirumala-gopuram.jpg",
    gallery: [
      "Pilgrims on the approach to the main temple",
      "Silathoranam, the natural rock arch near Tirumala",
      "The hills around Tirumala at sunrise",
    ],
    description: [
      "Tirupati's Sri Venkateswara Temple is one of the most visited pilgrimage sites on earth, and one of the most common weekend trips Bengaluru families make — we run it the way most people actually want it done: overnight travel so you don't burn a weekday, sorted logistics, and someone who knows the process handling the parts that trip up first-timers.",
      "Darshan queue times genuinely vary day to day and aren't something anyone can promise in advance — what we can promise is that you won't be figuring out tickets, queues or where to stay on your own.",
    ],
    highlights: [
      "Darshan at the Sri Venkateswara Temple, Tirumala",
      "Guidance through the ticket and queue process on the day",
      "Optional stop at Sri Padmavathi Temple, Tiruchanur",
      "Silathoranam natural rock arch and the Tirumala hills",
    ],
    itinerary: [
      {
        day: 1,
        title: "Overnight departure and Tirumala",
        items: [
          { time: "21:00", label: "Depart Bengaluru (Friday night)" },
          { time: "03:30", label: "Arrive Tirupati, check in, rest" },
          { time: "08:00", label: "Breakfast" },
          { time: "09:30", label: "Head up to Tirumala for darshan (queue time varies by day)" },
          { time: "18:00", label: "Return to Tirupati town, evening at leisure" },
        ],
      },
      {
        day: 2,
        title: "Local sightseeing and return",
        items: [
          { time: "08:00", label: "Breakfast" },
          { time: "09:00", label: "Sri Padmavathi Temple, Tiruchanur (optional)" },
          { time: "11:00", label: "Silathoranam and Tirumala hills viewpoint" },
          { time: "13:00", label: "Check out, depart for Bengaluru" },
          { time: "21:00", label: "Arrive Bengaluru, trip ends" },
        ],
      },
    ],
    inclusions: [
      "AC Tempo Traveller pickup and drop from Bengaluru",
      "1 night stay, twin sharing",
      "Breakfast both days",
      "Guidance through the darshan ticket and queue process",
      "Trip WhatsApp group with live updates",
    ],
    exclusions: [
      "Temple darshan/seva ticket fees (paid directly, options explained before the trip)",
      "Lunch and dinner both days",
      "Personal expenses, prasadam and shopping",
      "Anything not explicitly listed above",
    ],
    whoFor: [
      "Anyone who's been meaning to do a Tirupati trip and wants it planned end to end",
      "First-time group travellers who'd rather not navigate queues and tickets solo",
      "Families and larger groups going together",
    ],
    faqs: [
      { question: "How long is the darshan queue?", answer: "It genuinely varies by day and season — anywhere from a couple of hours to significantly longer on weekends and festival days. We'll walk you through ticket options (including special entry darshan) before the trip so you can decide what works for you." },
      { question: "Is there a dress code?", answer: "Yes — Tirumala enforces a dress code at the main temple: traditional wear is recommended, and shorts, t-shirts and casual western wear aren't allowed for men at some darshan lines. We'll share the exact rules before the trip." },
      { question: "How far is Tirupati from Bengaluru?", answer: "Around 250-270km via Chittoor, roughly 5-6 hours by road, which is why we travel overnight on Friday." },
      { question: "What's the cancellation policy?", answer: "Full details are on our Cancellation & Refund Policy page — in short, the earlier you cancel, the more you get back, and if Tripshala cancels a trip you get a full refund or a free move to another date." },
    ],
    isSample: true,
  },
  {
    id: "t20",
    slug: "adiyogi-isha-yoga-center-weekend",
    title: "Adiyogi & Isha Yoga Center Weekend",
    destination: "Coimbatore, Tamil Nadu",
    startingPoint: "Bengaluru (assembly point shared after booking)",
    date: "Next batch — ask on WhatsApp",
    duration: "2 Days / 1 Night (Friday night departure, back Sunday night)",
    transport: "Tempo Traveller",
    price: 6799,
    seatsTotal: 20,
    seatsLeft: 20,
    bookingStatus: "open",
    difficulty: "Easy",
    stay: "Guesthouse/hotel near Isha Yoga Center or Coimbatore, twin sharing",
    food: "Breakfast both days included, other meals on your own",
    categories: ["Temple Trails", "Weekend", "2 Days", "Heritage"],
    coverImageLabel: "The 112-foot Adiyogi Shiva statue at Isha Yoga Center, Coimbatore",
    coverImage: "/photos/adiyogi-statue-dusk.jpg",
    gallery: [
      "Adiyogi statue lit up at dusk",
      "The Dhyanalinga meditation dome",
      "Isha Yoga Center against the Velliangiri hills",
    ],
    description: [
      "Isha Yoga Center, at the foothills of the Velliangiri Mountains near Coimbatore, is home to two very different things worth the trip on their own — the 112-foot Adiyogi Shiva statue, a Guinness World Record-holder for the largest bust sculpture, and the Dhyanalinga, a unique meditative energy space designed by Sadhguru that doesn't belong to any one religion.",
      "It's a longer haul than our other temple trips, but it's also the one most people already have on their list — this trip handles the travel and logistics so a Coimbatore weekend actually happens instead of staying a someday plan.",
    ],
    highlights: [
      "The 112-foot Adiyogi statue, especially striking lit up in the evening",
      "A guided visit to the Dhyanalinga meditation space",
      "Isha's landscaped campus against the Velliangiri hills backdrop",
      "The evening 'Sounds of Isha' light and sound experience at the Adiyogi statue, timings permitting",
    ],
    itinerary: [
      {
        day: 1,
        title: "Overnight departure and Isha Yoga Center",
        items: [
          { time: "21:30", label: "Depart Bengaluru (Friday night)" },
          { time: "05:00", label: "Arrive Coimbatore, check in, rest" },
          { time: "08:00", label: "Breakfast" },
          { time: "09:30", label: "Adiyogi statue and Isha campus visit" },
          { time: "12:00", label: "Dhyanalinga meditation session" },
          { time: "13:30", label: "Lunch (on your own)" },
          { time: "18:30", label: "Evening at the Adiyogi statue (light and sound show, timings permitting)" },
        ],
      },
      {
        day: 2,
        title: "Leisure morning and return",
        items: [
          { time: "08:00", label: "Breakfast" },
          { time: "09:30", label: "Free time at Isha campus or local Coimbatore sightseeing" },
          { time: "12:30", label: "Check out, depart for Bengaluru" },
          { time: "20:00", label: "Arrive Bengaluru, trip ends" },
        ],
      },
    ],
    inclusions: [
      "AC Tempo Traveller pickup and drop from Bengaluru",
      "1 night stay, twin sharing",
      "Breakfast both days",
      "Trip WhatsApp group with live updates",
    ],
    exclusions: [
      "Lunch and dinner both days",
      "Any paid Isha program, therapy or session beyond general darshan/meditation visit",
      "Personal expenses and shopping",
      "Anything not explicitly listed above",
    ],
    whoFor: [
      "Anyone into meditation, mindfulness or Sadhguru's teachings",
      "Architecture and photography fans — the Adiyogi statue and Dhyanalinga are both striking spaces",
      "First-time visitors who've been meaning to make the trip but didn't want to plan it solo",
    ],
    faqs: [
      { question: "Is there a dress code?", answer: "Isha Yoga Center asks for modest, comfortable clothing — covered shoulders and knees is a safe default. We'll share the exact guidelines before the trip." },
      { question: "How far is Coimbatore from Bengaluru?", answer: "Around 370km, roughly 7 hours by road, which is why we travel overnight on Friday." },
      { question: "Do we need to book the Dhyanalinga session in advance?", answer: "Entry can get busy on weekends — we handle the group visit timing as part of the trip so you don't need to coordinate it yourself." },
      { question: "What's the cancellation policy?", answer: "Full details are on our Cancellation & Refund Policy page — in short, the earlier you cancel, the more you get back, and if Tripshala cancels a trip you get a full refund or a free move to another date." },
    ],
    isSample: true,
  },
];

export function getTripBySlug(slug: string): Trip | undefined {
  return trips.find((t) => t.slug === slug);
}

export const ALL_CATEGORIES: TripCategory[] = [
  "Bike Rides",
  "One Day",
  "Weekend",
  "2 Days",
  "Weekday",
  "Adventure",
  "Heritage",
  "Nature",
  "Trek",
  "Camping",
  "Coastal",
  "Wildlife",
  "Long Weekend",
  "Temple Trails",
];
